from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import logging
import os
import requests
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI()

# Allow frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# API Keys
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

class TextInput(BaseModel):
    text: str


class AIInput(BaseModel):
    text: str


# -----------
# Health Check
# -----------

@app.get("/")
def home():
    return {
        "status": "ready",
        "service": "veritext-backend",
        "endpoints": ["/health", "/api/plagiarism-check", "/api/ai-detect"],
    }


@app.get("/health")
def health():
    return {"status": "ok"}


# -----------
# Plagiarism Check (API-based)
# -----------

@app.post("/api/plagiarism-check")
def plagiarism_check(input: TextInput):
    """
    Analyze text for plagiarism using Gemini API.
    Returns similarity analysis and potential plagiarism indicators.
    """
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="Missing Gemini API key")

    try:
        # Limit text length
        text = input.text[:1000]

        prompt = f"""Analyze this text for plagiarism risk and provide similarity assessment.
        
Return ONLY valid JSON with no markdown, no backticks:
{{"plagiarism_risk": 0, "summary": "...", "reasons": []}}

plagiarism_risk: 0-100 score
summary: brief assessment
reasons: list of concerning patterns if any

Text to analyze:
{text}"""

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"

        response = requests.post(
            url,
            json={
                "contents": [{"parts": [{"text": prompt}]}],
                "generationConfig": {"temperature": 0.1}
            },
            timeout=20
        )

        if response.status_code != 200:
            raise HTTPException(status_code=500, detail="Gemini API failed")

        data = response.json()
        raw = data["candidates"][0]["content"]["parts"][0]["text"]
        clean = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(clean)

        return {
            "plagiarism_risk": parsed.get("plagiarism_risk", 0),
            "summary": parsed.get("summary", ""),
            "reasons": parsed.get("reasons", [])
        }

    except Exception as e:
        logger.error(f"Plagiarism check error: {e}")
        raise HTTPException(status_code=500, detail="Plagiarism analysis failed")


# -----------
# AI Detection Endpoint
# -----------

@app.post("/api/ai-detect")
def ai_detect(input: AIInput):
    """
    Detect if text was generated by AI using Gemini API.
    Returns probability scores for overall text and individual sentences.
    """
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="Missing Gemini API key")

    try:
        sentences = [
            s.strip() + "."
            for s in input.text.split(".")
            if len(s.strip()) > 5
        ]

        if not sentences:
            return {"overall": 0, "sentences": []}

        prompt = f"""You are an AI content detector. Analyze each sentence and estimate the probability (0-100) that it was written by an AI language model.

Return ONLY valid JSON with no markdown, no backticks, no explanation:
{{"overall":50,"sentences":[{{"text":"...","probability":50}}]}}

Sentences:
{chr(10).join(f"{i+1}. {s}" for i, s in enumerate(sentences))}"""

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"

        response = requests.post(
            url,
            json={
                "contents": [{"parts": [{"text": prompt}]}],
                "generationConfig": {"temperature": 0.1}
            },
            timeout=20
        )

        if response.status_code != 200:
            raise HTTPException(status_code=500, detail="Gemini API failed")

        data = response.json()
        raw = data["candidates"][0]["content"]["parts"][0]["text"]
        clean = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(clean)

        return {
            "overall": parsed.get("overall", 0),
            "sentences": parsed.get("sentences", [])
        }

    except Exception as e:
        logger.error(f"AI detection error: {e}")
        raise HTTPException(status_code=500, detail="AI detection failed")
